# Generated by Django 5.0.4 on 2024-04-25 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cetagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cetagory')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.cetagory')),
            ],
            options={
                'verbose_name_plural': 'Cetagories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('preview_des', models.CharField(max_length=300, verbose_name='Short Description')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('images1', models.ImageField(upload_to='img')),
                ('iamges2', models.ImageField(upload_to='img2')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_size', models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('ML', 'ML')], max_length=50)),
                ('is_stock', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cetagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.cetagory')),
            ],
        ),
    ]
