# Generated by Django 5.0.4 on 2024-04-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_sels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product', verbose_name='Add to Best Sels Product')),
            ],
            options={
                'verbose_name_plural': 'Best Sels',
            },
        ),
        migrations.CreateModel(
            name='hottrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product', verbose_name='Add Hot Trend Product')),
            ],
            options={
                'verbose_name_plural': 'Hot Trend',
            },
        ),
    ]
