# Generated by Django 5.0.4 on 2024-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_alter_orderplaced_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
