# Generated by Django 5.0.4 on 2024-04-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_alter_contract_names_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='mnb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
