# Generated by Django 5.0.4 on 2024-04-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_alter_sms_mnb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='cmm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sms',
            name='mkl',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
