# Generated by Django 5.0.4 on 2024-05-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
