# Generated by Django 5.0.4 on 2024-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='info',
            field=models.TextField(blank=True, verbose_name='Long Information'),
        ),
    ]
